version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/short_url-app:latest
    ports:
      - "8000:8000"
    environment:
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=database
      - DB_HOST=db
      - BASE_URL=http://localhost:8000
      - RATE_LIMIT_PER_MINUTE=5
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 10s
      timeout: 5s
      retries: 5

  cleaner:
    build:
      context: .
      dockerfile: cleaner/Dockerfile
    image: ${DOCKER_USERNAME}/short_url-cleaner:latest
    environment:
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=database
      - DB_HOST=db
    depends_on:
      - db